---
- name: install emacs 24
  homebrew: name=emacs install_options=cocoa

- name: remove emacs that ships with OS X
  script: remove-preinstalled
  when: ansible_os_family == 'Darwin'

- name: install prelude
  script: prelude

- name: copy personal.el
  copy: >
    dest=~/.emacs.d/personal/personal.el
    src=personal.el

- name: copy prelude-modules.el
  copy: >
    dest=~/.emacs.d/prelude-modules.el
    src=prelude-modules.el
